# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rspec-prof}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin MacKenzie IV"]
  s.date = %q{2010-07-13}
  s.description = %q{Integrates ruby-prof with RSpec, allowing you to easily profile your RSpec examples.}
  s.email = %q{sinisterchipmunk@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rspec-prof.rb",
     "lib/rspec-prof/profiler.rb",
     "pkg/rspec-prof-0.0.1.gem",
     "profiles/1-RSpecProf__should_profile_rspec.html",
     "profiles/2-RSpecProf__should_profile_rspec.txt",
     "profiles/3-RSpecProf__should_profile_rspec.txt",
     "profiles/5-RSpecProf__should_profile_rspec.html",
     "profiles/6-RSpecProf__should_profile_rspec.html",
     "profiles/7-RSpecProf_profile_multiple__before(:all).html",
     "rspec-prof.gemspec",
     "spec/rspec-prof_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sinisterchipmunk/rspec-prof}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Integrates ruby-prof with RSpec, allowing you to easily profile your RSpec examples.}
  s.test_files = [
    "spec/rspec-prof_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sc-core-ext>, [">= 1.2.1"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-prof>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<sc-core-ext>, [">= 1.2.1"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<ruby-prof>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<sc-core-ext>, [">= 1.2.1"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<ruby-prof>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

